local function packAdd(package)
  vim.api.nvim_command('packadd ' .. package)
end

packAdd('Comment.nvim')
packAdd('cmp-buffer')
packAdd('cmp-cmdline')
packAdd('cmp_luasnip')
packAdd('cmp-nvim-lsp')
packAdd('cmp-nvim-lua')
packAdd('cmp-path')
packAdd('friendly-snippets')
packAdd('LuaSnip')
packAdd('lualine.nvim')
packAdd('lspkind-nvim')
packAdd('nvim-autopairs')
packAdd('nvim-cmp')
packAdd('nvim-lspconfig')
packAdd('nvim-treesitter')
packAdd('nvim-web-devicons')
packAdd('playground')
packAdd('plenary.nvim')
packAdd('telescope.nvim')
packAdd('telescope-file-browser.nvim')
packAdd('telescope-ui-select.nvim')
packAdd('vim-fugitive')
packAdd('vim-rooter')
packAdd('vim-signify')
packAdd('vim-surround')
