local function packAdd(package)
  vim.api.nvim_command('packadd ' .. package)
end

packAdd('cmp-nvim-lsp')
packAdd('cmp-nvim-lua')
packAdd('lualine.nvim')
packAdd('nvim-autopairs')
packAdd('nvim-cmp')
packAdd('nvim-lspconfig')
packAdd('nvim-treesitter')
packAdd('nvim-web-devicons')
packAdd('playground')
packAdd('plenary.nvim')
packAdd('telescope.nvim')
packAdd('vim-commentary')
packAdd('vim-fugitive')
packAdd('vim-rooter')
packAdd('vim-signify')
packAdd('vim-surround')
