local function packAdd(package)
  vim.api.nvim_command('packadd ' .. package)
end

packAdd('auto-pairs')
packAdd('completion-nvim')
packAdd('haskell-vim')
packAdd('lualine.nvim')
packAdd('nvim-lspconfig')
packAdd('nvim-treesitter')
packAdd('nvim-web-devicons')
packAdd('plenary.nvim')
packAdd('popup.nvim')
packAdd('telescope.nvim')
packAdd('vim-commentary')
packAdd('vim-fugitive')
packAdd('vim-rooter')
packAdd('vim-signify')
packAdd('vim-surround')
